import { describe,expect,it,vi } from 'vitest'
import { isCorrectAnswer,normalizeAnswer } from '../services/answerValidator'
import { buildClozeSentence } from '../services/clozeBuilder'
import { hideReveal,initialAttemptState,submitAttempt } from '../services/practiceSession'
import { SpacedRepetitionScheduler } from '../services/spacedRepetition'
import { selectCards } from '../services/cardSelector'
import type { LoadedVocabulary } from '../domain/vocabulary'
import type { LearningProgress } from '../domain/learningProgress'
import { parseVocabularyUpload } from '../services/uploadValidator'
import { endOfLocalDay,getHomeStats } from '../services/homeStats'
const card=(overrides:Partial<LoadedVocabulary>={}):LoadedVocabulary=>({id:'x',category:'test',lemma:'strawberry',sentence:'eat fresh strawberries',translation:'吃新鲜草莓',answer:'strawberries',targetType:'word',dataset:'vocabulary',...overrides})
describe('answerValidator',()=>{it.each(['postpone','POSTPONE',' Postpone '])('normalizes %s',v=>expect(normalizeAnswer(v)).toBe('postpone'));it('normalizes phrase spaces',()=>expect(isCorrectAnswer('air   conditioning',{answer:'air conditioning'})).toBe(true));it('accepts aliases',()=>expect(isCorrectAnswer('travelled',{answer:'traveled',aliases:['travelled']})).toBe(true));it('does not accept lemma or other forms',()=>{expect(isCorrectAnswer('strawberry',card())).toBe(false);const begin=card({lemma:'begin',answer:'began'});for(const wrong of ['begin','begun','beginning'])expect(isCorrectAnswer(wrong,begin)).toBe(false)})})
describe('clozeBuilder',()=>{it('clozes the answer',()=>expect(buildClozeSentence('eat fresh strawberries','strawberries')).toMatchObject({before:'eat fresh ',after:'',found:true}));it('clozes a complete phrase',()=>{const c=buildClozeSentence('turn on the air conditioning','air conditioning');expect(c.before).toBe('turn on the ');expect(c.blank).toHaveLength(16)})})
describe('practice state',()=>{it('reveals after three errors, hides, and still requires input',()=>{let s=initialAttemptState();for(let i=0;i<3;i++)s=submitAttempt(card(),s,'wrong');expect(s).toMatchObject({wrongAttempts:3,reveal:true,complete:false});s=hideReveal(s);expect(s.reveal).toBe(false);expect(s.complete).toBe(false);s=submitAttempt(card(),s,'strawberries');expect(s.complete).toBe(true)})})
describe('scheduler',()=>{it('increases clean intervals and reduces after errors',()=>{const scheduler=new SpacedRepetitionScheduler(),now=100000;const one=scheduler.schedule(undefined,{vocabularyId:'x',attempts:1,wrongAttempts:0,firstTryCorrect:true,eventuallyCorrect:true,reviewedAt:now});const two=scheduler.schedule(one,{vocabularyId:'x',attempts:1,wrongAttempts:0,firstTryCorrect:true,eventuallyCorrect:true,reviewedAt:now});expect(two.nextReviewAt!-now).toBeGreaterThan(one.nextReviewAt!-now);const wrong=scheduler.schedule(two,{vocabularyId:'x',attempts:3,wrongAttempts:2,firstTryCorrect:false,eventuallyCorrect:true,reviewedAt:now});expect(wrong.nextReviewAt!-now).toBeLessThan(two.nextReviewAt!-now)})})
describe('cardSelector',()=>{it('prioritizes overdue, then error rate; limits and de-duplicates',()=>{const cards=[card({id:'new'}),card({id:'error'}),card({id:'due'})],progress:Record<string,LearningProgress>={error:{vocabularyId:'error',status:'review',totalReviews:2,correctCount:1,incorrectCount:4,firstTryCorrectCount:0,streak:0},due:{vocabularyId:'due',status:'review',totalReviews:1,correctCount:1,incorrectCount:0,firstTryCorrectCount:1,streak:1,nextReviewAt:5}};const selected=selectCards(cards,progress,{mode:'mixed',limit:2,now:10,random:()=>0});expect(selected.map(c=>c.id)).toEqual(['due','error']);expect(new Set(selected.map(c=>c.id)).size).toBe(2)});it('excludes recently used ids',()=>expect(selectCards([card({id:'a'}),card({id:'b'})],{},{mode:'mixed',excludeIds:['a'],random:vi.fn(()=>0)}).map(c=>c.id)).toEqual(['b']))})
describe('uploadValidator',()=>{it('accepts an items document',()=>{const parsed=parseVocabularyUpload(JSON.stringify({items:[card()]}));expect(parsed.items).toHaveLength(1);expect(parsed.errors).toHaveLength(0)});it('rejects invalid and duplicate cards without importing them',()=>{const parsed=parseVocabularyUpload(JSON.stringify([card(),card(),card({id:'bad',sentence:'no target'})]));expect(parsed.items).toHaveLength(1);expect(parsed.errors).toHaveLength(2)})})
describe('homeStats',()=>{it('counts reviews due later today and separates learning from mastered',()=>{const now=new Date(2026,7,26,10).getTime(),cards=[card({id:'learning'}),card({id:'mastered'}),card({id:'new'})],progress:Record<string,LearningProgress>={learning:{vocabularyId:'learning',status:'review',totalReviews:1,correctCount:1,incorrectCount:0,firstTryCorrectCount:1,streak:1,nextReviewAt:now+60_000},mastered:{vocabularyId:'mastered',status:'mastered',totalReviews:6,correctCount:6,incorrectCount:0,firstTryCorrectCount:6,streak:6,nextReviewAt:endOfLocalDay(now)+1}};expect(getHomeStats(cards,progress,now)).toEqual({dueToday:1,learning:1,newCount:1,mastered:1})});it('ignores stale progress for cards no longer in the library',()=>{const stale:LearningProgress={vocabularyId:'removed',status:'mastered',totalReviews:6,correctCount:6,incorrectCount:0,firstTryCorrectCount:6,streak:6};expect(getHomeStats([card()],{removed:stale},0)).toEqual({dueToday:0,learning:0,newCount:1,mastered:0})})})
