import { describe,expect,it,vi } from 'vitest'
import { isCorrectAnswer,normalizeAnswer } from '../services/answerValidator'
import { buildClozeSentence } from '../services/clozeBuilder'
import { hideReveal,initialAttemptState,submitAttempt } from '../services/practiceSession'
import { SpacedRepetitionScheduler } from '../services/spacedRepetition'
import { selectCards } from '../services/cardSelector'
import type { LoadedVocabulary } from '../domain/vocabulary'
import type { LearningProgress } from '../domain/learningProgress'
import type { ReviewResult } from '../domain/reviewResult'
import { parseVocabularyUpload } from '../services/uploadValidator'
import { endOfLocalDay,getHomeStats } from '../services/homeStats'
import { act,fireEvent,render,screen } from '@testing-library/react'
import { answerRevealDuration,PracticeCard } from '../components/PracticeCard'
import { createElement } from 'react'
const card=(overrides:Partial<LoadedVocabulary>={}):LoadedVocabulary=>({id:'x',category:'test',lemma:'strawberry',sentence:'eat fresh strawberries',translation:'吃新鲜草莓',answer:'strawberries',targetType:'word',dataset:'vocabulary',...overrides})
describe('answerValidator',()=>{it.each(['postpone','POSTPONE',' Postpone '])('normalizes %s',v=>expect(normalizeAnswer(v)).toBe('postpone'));it('normalizes phrase spaces',()=>expect(isCorrectAnswer('air   conditioning',{answer:'air conditioning'})).toBe(true));it('accepts aliases',()=>expect(isCorrectAnswer('travelled',{answer:'traveled',aliases:['travelled']})).toBe(true));it('does not accept lemma or other forms',()=>{expect(isCorrectAnswer('strawberry',card())).toBe(false);const begin=card({lemma:'begin',answer:'began'});for(const wrong of ['begin','begun','beginning'])expect(isCorrectAnswer(wrong,begin)).toBe(false)})})
describe('clozeBuilder',()=>{it('clozes the answer',()=>expect(buildClozeSentence('eat fresh strawberries','strawberries')).toMatchObject({before:'eat fresh ',after:'',found:true}));it('clozes a complete phrase',()=>{const c=buildClozeSentence('turn on the air conditioning','air conditioning');expect(c.before).toBe('turn on the ');expect(c.blank).toHaveLength(16)})})
describe('practice state',()=>{it('reveals after three errors, hides, and still requires input',()=>{let s=initialAttemptState();for(let i=0;i<3;i++)s=submitAttempt(card(),s,'wrong');expect(s).toMatchObject({wrongAttempts:3,reveal:true,complete:false});s=hideReveal(s);expect(s.reveal).toBe(false);expect(s.complete).toBe(false);s=submitAttempt(card(),s,'strawberries');expect(s.complete).toBe(true)})})
describe('PracticeCard answer reveal',()=>{it('uses 3 seconds for writing and 1 second for other datasets',()=>{expect(answerRevealDuration(card({dataset:'writing'}))).toBe(3000);expect(answerRevealDuration(card())).toBe(1000)});it('focuses the input after the revealed answer is hidden',()=>{vi.useFakeTimers();render(createElement(PracticeCard,{card:card(),onComplete:()=>{}}));const input=screen.getByPlaceholderText('输入答案，按 Enter 提交') as HTMLInputElement;for(let i=0;i<3;i++){fireEvent.change(input,{target:{value:'wrong'}});fireEvent.submit(input.closest('form')!)}expect(input.disabled).toBe(true);act(()=>vi.advanceTimersByTime(1000));act(()=>vi.runOnlyPendingTimers());expect(input.disabled).toBe(false);expect(document.activeElement).toBe(input);vi.useRealTimers()})})
describe('scheduler',()=>{const clean=(reviewedAt:number):ReviewResult=>({vocabularyId:'x',attempts:1,wrongAttempts:0,firstTryCorrect:true,eventuallyCorrect:true,reviewedAt});it('marks a word mastered after three spaced first-try correct reviews',()=>{const scheduler=new SpacedRepetitionScheduler(),one=scheduler.schedule(undefined,clean(100_000)),two=scheduler.schedule(one,clean(one.nextReviewAt!)),three=scheduler.schedule(two,clean(two.nextReviewAt!));expect(one).toMatchObject({streak:1,status:'review'});expect(two).toMatchObject({streak:2,status:'review'});expect(three).toMatchObject({streak:3,status:'mastered'});expect(three.nextReviewAt!-two.nextReviewAt!).toBe(3*86_400_000)});it('does not advance the streak when reviewed before it is due',()=>{const scheduler=new SpacedRepetitionScheduler(),one=scheduler.schedule(undefined,clean(100_000)),early=scheduler.schedule(one,clean(100_001));expect(early.streak).toBe(1);expect(early.nextReviewAt).toBe(one.nextReviewAt)});it('demotes a mastered word and resets its clean streak after an error',()=>{const scheduler=new SpacedRepetitionScheduler(),one=scheduler.schedule(undefined,clean(100_000)),two=scheduler.schedule(one,clean(one.nextReviewAt!)),three=scheduler.schedule(two,clean(two.nextReviewAt!)),wrong=scheduler.schedule(three,{vocabularyId:'x',attempts:2,wrongAttempts:1,firstTryCorrect:false,eventuallyCorrect:true,reviewedAt:three.nextReviewAt!});expect(wrong).toMatchObject({streak:0,status:'review'});expect(wrong.nextReviewAt!-three.nextReviewAt!).toBe(7*60_000)})})
describe('cardSelector',()=>{it('keeps overdue first, then reserves space for new cards',()=>{const cards=[card({id:'new'}),card({id:'error'}),card({id:'due'})],progress:Record<string,LearningProgress>={error:{vocabularyId:'error',status:'review',totalReviews:2,correctCount:1,incorrectCount:4,firstTryCorrectCount:0,streak:0},due:{vocabularyId:'due',status:'review',totalReviews:1,correctCount:1,incorrectCount:0,firstTryCorrectCount:1,streak:1,nextReviewAt:5}};const selected=selectCards(cards,progress,{mode:'mixed',limit:2,now:10,random:()=>0});expect(selected.map(c=>c.id)).toEqual(['due','new']);expect(new Set(selected.map(c=>c.id)).size).toBe(2)});it('excludes recently used ids',()=>expect(selectCards([card({id:'a'}),card({id:'b'})],{},{mode:'mixed',excludeIds:['a'],random:vi.fn(()=>0)}).map(c=>c.id)).toEqual(['b']));it('keeps writing practice separate from other datasets',()=>{const cards=[card({id:'general'}),card({id:'writing',dataset:'writing',answer:'in the long term'})];expect(selectCards(cards,{}, {mode:'writing',random:()=>0}).map(c=>c.id)).toEqual(['writing'])})})
describe('cardSelector session balance',()=>{const reviewed=(id:string):LearningProgress=>({vocabularyId:id,status:'review',totalReviews:1,correctCount:1,incorrectCount:0,firstTryCorrectCount:1,streak:1,lastReviewedAt:100,nextReviewAt:10_000});it('uses 80% new cards when enough are available',()=>{const fresh=Array.from({length:20},(_,i)=>card({id:`new-${i}`})),old=Array.from({length:20},(_,i)=>card({id:`old-${i}`})),progress=Object.fromEntries(old.map(c=>[c.id,reviewed(c.id)]));const selected=selectCards([...old,...fresh],progress,{mode:'mixed',limit:20,now:1000,random:()=>0});expect(selected).toHaveLength(20);expect(selected.filter(c=>!progress[c.id])).toHaveLength(16)});it('does not repeat cards from the previous group when other candidates exist',()=>{const previous=Array.from({length:20},(_,i)=>card({id:`previous-${i}`})),other=Array.from({length:20},(_,i)=>card({id:`other-${i}`})),selected=selectCards([...previous,...other],{},{mode:'mixed',limit:20,excludeIds:previous.map(c=>c.id),random:vi.fn(()=>0)});expect(selected).toHaveLength(20);expect(selected.some(c=>c.id.startsWith('previous-'))).toBe(false)});it('reserves 80% for new cards even when many reviews are overdue',()=>{const overdue=Array.from({length:20},(_,i)=>card({id:`due-${i}`})),fresh=Array.from({length:20},(_,i)=>card({id:`new-${i}`})),progress=Object.fromEntries(overdue.map(c=>[c.id,{...reviewed(c.id),nextReviewAt:1}]));const selected=selectCards([...fresh,...overdue],progress,{mode:'mixed',limit:20,now:100,random:()=>0});expect(selected.filter(c=>c.id.startsWith('new-'))).toHaveLength(16);expect(selected.filter(c=>c.id.startsWith('due-'))).toHaveLength(4)});it('fills remaining slots with reviews when fewer new cards are available',()=>{const fresh=Array.from({length:3},(_,i)=>card({id:`new-${i}`})),old=Array.from({length:20},(_,i)=>card({id:`old-${i}`})),progress=Object.fromEntries(old.map(c=>[c.id,reviewed(c.id)]));const selected=selectCards([...old,...fresh],progress,{mode:'mixed',limit:20,now:1000,random:()=>0});expect(selected).toHaveLength(20);expect(selected.filter(c=>!progress[c.id])).toHaveLength(3)});it('uses a not-due mastered word only after active reviews are exhausted',()=>{const active=card({id:'active'}),mastered=card({id:'mastered'}),progress={active:reviewed('active'),mastered:{...reviewed('mastered'),status:'mastered' as const,streak:3}};expect(selectCards([mastered,active],progress,{mode:'mixed',limit:1,now:1000,random:()=>0}).map(c=>c.id)).toEqual(['active'])})})
describe('uploadValidator',()=>{it('accepts an items document',()=>{const parsed=parseVocabularyUpload(JSON.stringify({items:[card()]}));expect(parsed.items).toHaveLength(1);expect(parsed.errors).toHaveLength(0)});it('rejects invalid and duplicate cards without importing them',()=>{const parsed=parseVocabularyUpload(JSON.stringify([card(),card(),card({id:'bad',sentence:'no target'})]));expect(parsed.items).toHaveLength(1);expect(parsed.errors).toHaveLength(2)})})
describe('homeStats',()=>{it('counts reviews due later today and separates learning from mastered',()=>{const now=new Date(2026,7,26,10).getTime(),cards=[card({id:'learning'}),card({id:'mastered'}),card({id:'new'})],progress:Record<string,LearningProgress>={learning:{vocabularyId:'learning',status:'review',totalReviews:1,correctCount:1,incorrectCount:0,firstTryCorrectCount:1,streak:1,nextReviewAt:now+60_000},mastered:{vocabularyId:'mastered',status:'mastered',totalReviews:6,correctCount:6,incorrectCount:0,firstTryCorrectCount:6,streak:6,nextReviewAt:endOfLocalDay(now)+1}};expect(getHomeStats(cards,progress,now)).toEqual({dueToday:1,learning:1,newCount:1,mastered:1})});it('ignores stale progress for cards no longer in the library',()=>{const stale:LearningProgress={vocabularyId:'removed',status:'mastered',totalReviews:6,correctCount:6,incorrectCount:0,firstTryCorrectCount:6,streak:6};expect(getHomeStats([card()],{removed:stale},0)).toEqual({dueToday:0,learning:0,newCount:1,mastered:0})})})
