-- Run in the Supabase SQL Editor to enable sentence dictation history.
create table if not exists public.sentence_dictation_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  session_id uuid not null,
  vocabulary_id text not null,
  dataset text not null,
  sentence_snapshot text not null,
  translation_snapshot text not null,
  submitted_answer text not null default '',
  normalized_answer text not null default '',
  is_correct boolean not null default false,
  accuracy integer not null check (accuracy between 0 and 100),
  word_differences jsonb not null default '[]'::jsonb,
  attempt_number integer not null default 1 check (attempt_number > 0),
  submission_type text not null check (submission_type in ('initial','skipped')),
  submitted_at timestamptz not null default now()
);

alter table public.sentence_dictation_attempts
  add column if not exists word_differences jsonb not null default '[]'::jsonb;

create index if not exists dictation_attempts_user_sentence_time_idx
  on public.sentence_dictation_attempts (user_id, vocabulary_id, submitted_at desc);
create index if not exists dictation_attempts_user_time_idx
  on public.sentence_dictation_attempts (user_id, submitted_at desc);

create or replace function public.assign_dictation_attempt_number()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.user_id := auth.uid();
  if new.user_id is null then raise exception 'Authentication required'; end if;
  select coalesce(max(attempt_number), 0) + 1 into new.attempt_number
  from public.sentence_dictation_attempts
  where user_id = new.user_id and vocabulary_id = new.vocabulary_id
    and submission_type = 'initial';
  return new;
end;
$$;

drop trigger if exists assign_dictation_attempt_number_before_insert on public.sentence_dictation_attempts;
create trigger assign_dictation_attempt_number_before_insert
  before insert on public.sentence_dictation_attempts
  for each row execute function public.assign_dictation_attempt_number();

alter table public.sentence_dictation_attempts enable row level security;
drop policy if exists "users insert own dictation attempts" on public.sentence_dictation_attempts;
create policy "users insert own dictation attempts" on public.sentence_dictation_attempts
  for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "users read own dictation attempts" on public.sentence_dictation_attempts;
create policy "users read own dictation attempts" on public.sentence_dictation_attempts
  for select to authenticated using ((select auth.uid()) = user_id);

grant select, insert on public.sentence_dictation_attempts to authenticated;
revoke all on function public.assign_dictation_attempt_number() from public;
