-- Run after schema.sql. Safe to run again when upgrading an existing project.
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null unique check (char_length(nickname) between 2 and 24 and position('@' in nickname) = 0),
  leaderboard_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.practice_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  vocabulary_id text not null,
  reviewed_at timestamptz not null default now(),
  first_try_correct boolean not null,
  wrong_attempts integer not null check (wrong_attempts >= 0),
  eventually_correct boolean not null,
  became_mastered boolean not null default false,
  earned_points integer not null check (earned_points >= 0)
);

create index if not exists practice_events_user_reviewed_idx
  on public.practice_events (user_id, reviewed_at desc);

create table if not exists public.daily_learning_stats (
  user_id uuid not null references auth.users(id) on delete cascade,
  stat_date date not null,
  completed_count integer not null default 0,
  first_try_correct_count integer not null default 0,
  new_mastered_count integer not null default 0,
  points integer not null default 0 check (points between 0 and 300),
  primary key (user_id, stat_date)
);

alter table public.profiles enable row level security;
alter table public.practice_events enable row level security;
alter table public.daily_learning_stats enable row level security;

do $$ begin
  alter table public.profiles add constraint profiles_nickname_not_email
    check (position('@' in nickname) = 0);
exception when duplicate_object then null;
end $$;

drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
drop policy if exists "users read own practice events" on public.practice_events;
create policy "users read own practice events" on public.practice_events
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "users read own daily stats" on public.daily_learning_stats;
create policy "users read own daily stats" on public.daily_learning_stats
  for select to authenticated using ((select auth.uid()) = user_id);

grant select, update on public.profiles to authenticated;
grant select on public.practice_events, public.daily_learning_stats to authenticated;

create or replace function public.default_nickname(user_email text, user_id uuid)
returns text
language plpgsql
stable
set search_path = public
as $$
declare
  base text := left(coalesce(nullif(split_part(user_email, '@', 1), ''), 'learner'), 24);
begin
  if char_length(base) < 2 then base := base || '-' || left(user_id::text, 4); end if;
  if not exists (select 1 from public.profiles where nickname = base) then return base; end if;
  return left(base, 15) || '-' || left(user_id::text, 8);
end;
$$;

create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, nickname)
  values (new.id, public.default_nickname(coalesce(new.email, 'learner'), new.id))
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup
  after insert on auth.users
  for each row execute function public.create_profile_for_new_user();

do $$
declare existing_user record;
begin
  for existing_user in
    select u.id, u.email from auth.users u
    where not exists (select 1 from public.profiles p where p.user_id = u.id)
    order by u.created_at
  loop
    insert into public.profiles (user_id, nickname)
    values (
      existing_user.id,
      public.default_nickname(coalesce(existing_user.email, 'learner'), existing_user.id)
    )
    on conflict (user_id) do nothing;
  end loop;
end;
$$;

create or replace function public.record_practice_result(
  p_vocabulary_id text,
  p_first_try_correct boolean,
  p_wrong_attempts integer,
  p_eventually_correct boolean,
  p_became_mastered boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  local_date date := (timezone('Asia/Shanghai', now()))::date;
  previous_completed integer;
  base_points integer;
  awarded_points integer;
  first_mastery boolean;
begin
  if current_user_id is null then raise exception 'Authentication required'; end if;
  if p_wrong_attempts < 0 then raise exception 'Invalid wrong attempt count'; end if;

  select completed_count into previous_completed
  from public.daily_learning_stats
  where user_id = current_user_id and stat_date = local_date;
  previous_completed := coalesce(previous_completed, 0);
  first_mastery := p_became_mastered and not exists (
    select 1 from public.practice_events
    where user_id = current_user_id
      and vocabulary_id = p_vocabulary_id
      and became_mastered
  );
  base_points := case when p_first_try_correct then 10 when p_eventually_correct then 5 else 0 end
    + case when first_mastery then 20 else 0 end;
  awarded_points := base_points + case when previous_completed = 19 then 20 else 0 end;

  insert into public.practice_events (
    user_id, vocabulary_id, first_try_correct, wrong_attempts,
    eventually_correct, became_mastered, earned_points
  ) values (
    current_user_id, p_vocabulary_id, p_first_try_correct, p_wrong_attempts,
    p_eventually_correct, first_mastery, awarded_points
  );

  insert into public.daily_learning_stats (
    user_id, stat_date, completed_count, first_try_correct_count, new_mastered_count, points
  ) values (
    current_user_id, local_date, 1, p_first_try_correct::integer,
    first_mastery::integer, least(300, awarded_points)
  )
  on conflict (user_id, stat_date) do update set
    completed_count = daily_learning_stats.completed_count + 1,
    first_try_correct_count = daily_learning_stats.first_try_correct_count + excluded.first_try_correct_count,
    new_mastered_count = daily_learning_stats.new_mastered_count + excluded.new_mastered_count,
    points = least(300, daily_learning_stats.points + excluded.points);
end;
$$;

-- Re-identify historical first mastery events using three consecutive,
-- correctly spaced first-try recalls. This also upgrades v1/v2 event data.
with ordered_events as (
  select e.id, e.user_id, e.vocabulary_id, e.reviewed_at, e.first_try_correct,
    lag(e.first_try_correct, 1) over word_history as previous_correct,
    lag(e.first_try_correct, 2) over word_history as two_back_correct,
    lag(e.reviewed_at, 1) over word_history as previous_reviewed_at,
    lag(e.reviewed_at, 2) over word_history as two_back_reviewed_at
  from public.practice_events e
  window word_history as (
    partition by e.user_id, e.vocabulary_id order by e.reviewed_at, e.id
  )
), mastery_candidates as (
  select *, row_number() over (
    partition by user_id, vocabulary_id order by reviewed_at, id
  ) as mastery_number
  from ordered_events
  where first_try_correct and previous_correct and two_back_correct
    and previous_reviewed_at - two_back_reviewed_at >= interval '10 minutes'
    and reviewed_at - previous_reviewed_at >= interval '1 day'
), first_masteries as (
  select id from mastery_candidates where mastery_number = 1
)
update public.practice_events e
set became_mastered = exists (select 1 from first_masteries m where m.id = e.id);

-- Rebuild leaderboard aggregates after applying the three-recall rule.
with marked_events as (
  select e.*,
    (timezone('Asia/Shanghai', e.reviewed_at))::date as local_date,
    row_number() over (
      partition by e.user_id, (timezone('Asia/Shanghai', e.reviewed_at))::date
      order by e.reviewed_at, e.id
    ) as daily_sequence
  from public.practice_events e
), rebuilt as (
  select user_id, local_date,
    count(*)::integer as completed_count,
    count(*) filter (where first_try_correct)::integer as first_try_correct_count,
    count(*) filter (where became_mastered)::integer as new_mastered_count,
    least(300, sum(
      case when first_try_correct then 10 when eventually_correct then 5 else 0 end
      + case when became_mastered then 20 else 0 end
      + case when daily_sequence = 20 then 20 else 0 end
    ))::integer as points
  from marked_events
  group by user_id, local_date
)
update public.daily_learning_stats d set
  completed_count = r.completed_count,
  first_try_correct_count = r.first_try_correct_count,
  new_mastered_count = r.new_mastered_count,
  points = r.points
from rebuilt r
where d.user_id = r.user_id and d.stat_date = r.local_date;

create or replace function public.current_learning_streak(p_user_id uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with recent as (
    select max(stat_date) as anchor
    from public.daily_learning_stats
    where user_id = p_user_id
      and stat_date >= (timezone('Asia/Shanghai', now()))::date - 1
  ), numbered as (
    select stat_date,
      stat_date + (row_number() over (order by stat_date desc))::integer as island
    from public.daily_learning_stats, recent
    where user_id = p_user_id and stat_date <= recent.anchor
  )
  select coalesce(count(*) filter (
    where island = (select anchor + 1 from recent)
  ), 0)::integer from numbered;
$$;

create or replace function public.get_learning_leaderboard(p_period text default 'week')
returns table (
  rank bigint,
  nickname text,
  points bigint,
  completed_count bigint,
  new_mastered_count bigint,
  accuracy numeric,
  study_streak integer,
  is_current_user boolean
)
language sql
stable
security definer
set search_path = public
as $$
  with bounds as (
    select case p_period
      when 'today' then (timezone('Asia/Shanghai', now()))::date
      when 'week' then date_trunc('week', timezone('Asia/Shanghai', now()))::date
      when 'all' then null::date
      else date_trunc('week', timezone('Asia/Shanghai', now()))::date
    end as start_date
  ), totals as (
    select p.user_id, p.nickname,
      coalesce(sum(d.points), 0)::bigint as points,
      coalesce(sum(d.completed_count), 0)::bigint as completed_count,
      coalesce(sum(d.first_try_correct_count), 0)::bigint as first_correct,
      coalesce(sum(d.new_mastered_count), 0)::bigint as new_mastered_count
    from public.profiles p
    cross join bounds b
    left join public.daily_learning_stats d on d.user_id = p.user_id
      and (b.start_date is null or d.stat_date >= b.start_date)
    where p.leaderboard_enabled
    group by p.user_id, p.nickname
  ), ranked as (
    select dense_rank() over (
      order by points desc, new_mastered_count desc,
        case when completed_count = 0 then 0 else first_correct::numeric / completed_count end desc
    ) as rank, *
    from totals
  )
  select r.rank, r.nickname, r.points, r.completed_count, r.new_mastered_count,
    case when r.completed_count = 0 then 0
      else round(r.first_correct::numeric * 100 / r.completed_count, 1) end as accuracy,
    public.current_learning_streak(r.user_id) as study_streak,
    r.user_id = auth.uid() as is_current_user
  from ranked r
  order by r.rank, r.nickname;
$$;

revoke all on function public.record_practice_result(text, boolean, integer, boolean, boolean) from public;
revoke all on function public.get_learning_leaderboard(text) from public;
revoke all on function public.default_nickname(text, uuid) from public;
revoke all on function public.create_profile_for_new_user() from public;
revoke all on function public.current_learning_streak(uuid) from public;
grant execute on function public.record_practice_result(text, boolean, integer, boolean, boolean) to authenticated;
grant execute on function public.get_learning_leaderboard(text) to authenticated;
