import type { User } from '@supabase/supabase-js'
import type { LearningProgress } from '../domain/learningProgress'
import type { ReviewResult } from '../domain/reviewResult'
import type { LoadedVocabulary,VocabularySource } from '../domain/vocabulary'
import { supabase } from '../lib/supabase'
export interface UserProfile { nickname:string; leaderboardEnabled:boolean }
export interface LeaderboardEntry { rank:number;nickname:string;points:number;completedCount:number;newMasteredCount:number;accuracy:number;studyStreak:number;isCurrentUser:boolean }
export type LeaderboardPeriod='today'|'week'|'all'
const progressFromRow=(r:Record<string,unknown>):LearningProgress=>({vocabularyId:r.vocabulary_id as string,status:r.status as LearningProgress['status'],totalReviews:r.total_reviews as number,correctCount:r.correct_count as number,incorrectCount:r.incorrect_count as number,firstTryCorrectCount:r.first_try_correct_count as number,streak:r.streak as number,lastReviewedAt:r.last_reviewed_at as number|undefined,nextReviewAt:r.next_review_at as number|undefined,lastWrongAttempts:r.last_wrong_attempts as number|undefined,ease:r.ease as number|undefined})
export async function loadCloudProgress(){if(!supabase)return{};const {data,error}=await supabase.from('learning_progress').select('*');if(error)throw error;return Object.fromEntries((data??[]).map(r=>[r.vocabulary_id,progressFromRow(r)])) as Record<string,LearningProgress>}
export async function saveCloudProgress(user:User,p:LearningProgress){if(!supabase)return;const {error}=await supabase.from('learning_progress').upsert({user_id:user.id,vocabulary_id:p.vocabularyId,status:p.status,total_reviews:p.totalReviews,correct_count:p.correctCount,incorrect_count:p.incorrectCount,first_try_correct_count:p.firstTryCorrectCount,streak:p.streak,last_reviewed_at:p.lastReviewedAt,next_review_at:p.nextReviewAt,last_wrong_attempts:p.lastWrongAttempts,ease:p.ease,updated_at:new Date().toISOString()});if(error)throw error}
export async function loadUserVocabulary():Promise<LoadedVocabulary[]>{if(!supabase)return[];const {data,error}=await supabase.from('user_vocabulary').select('*').order('created_at');if(error)throw error;return(data??[]).map(r=>({id:r.id,category:r.category,categoryZh:r.category_zh,conceptGroup:r.concept_group,lemma:r.lemma,sentence:r.sentence,translation:r.translation,answer:r.answer,targetType:r.target_type,aliases:r.aliases,confusionGroup:r.confusion_group,tags:r.tags,difficulty:r.difficulty,dataset:'custom'}))}
export async function uploadUserVocabulary(user:User,items:VocabularySource[]){if(!supabase)return;const rows=items.map(c=>({user_id:user.id,id:`custom:${c.id}`,category:c.category||'My Vocabulary',category_zh:c.categoryZh,concept_group:c.conceptGroup,lemma:c.lemma,sentence:c.sentence,translation:c.translation,answer:c.answer,target_type:c.targetType,aliases:c.aliases??[],confusion_group:c.confusionGroup,tags:c.tags??[],difficulty:c.difficulty??1}));const {error}=await supabase.from('user_vocabulary').upsert(rows);if(error)throw error}
export async function loadUserProfile():Promise<UserProfile|undefined>{if(!supabase)return;const {data,error}=await supabase.from('profiles').select('nickname,leaderboard_enabled').maybeSingle();if(error)throw error;return data?{nickname:data.nickname,leaderboardEnabled:data.leaderboard_enabled}:undefined}
export async function updateUserProfile(profile:UserProfile){if(!supabase)return;const {error}=await supabase.from('profiles').update({nickname:profile.nickname.trim(),leaderboard_enabled:profile.leaderboardEnabled,updated_at:new Date().toISOString()}).eq('user_id',(await supabase.auth.getUser()).data.user?.id);if(error)throw error}
export async function recordPracticeEvent(result:ReviewResult,becameMastered:boolean){if(!supabase)return;const {error}=await supabase.rpc('record_practice_result',{p_vocabulary_id:result.vocabularyId,p_first_try_correct:result.firstTryCorrect,p_wrong_attempts:result.wrongAttempts,p_eventually_correct:result.eventuallyCorrect,p_became_mastered:becameMastered});if(error)throw error}
export async function loadLeaderboard(period:LeaderboardPeriod):Promise<LeaderboardEntry[]>{if(!supabase)return[];const {data,error}=await supabase.rpc('get_learning_leaderboard',{p_period:period});if(error)throw error;return(data??[]).map((r:Record<string,unknown>)=>({rank:Number(r.rank),nickname:String(r.nickname),points:Number(r.points),completedCount:Number(r.completed_count),newMasteredCount:Number(r.new_mastered_count),accuracy:Number(r.accuracy),studyStreak:Number(r.study_streak),isCurrentUser:Boolean(r.is_current_user)}))}
