import type { User } from '@supabase/supabase-js'
import type { LearningProgress } from '../domain/learningProgress'
import type { LoadedVocabulary,VocabularySource } from '../domain/vocabulary'
import { supabase } from '../lib/supabase'
const progressFromRow=(r:Record<string,unknown>):LearningProgress=>({vocabularyId:r.vocabulary_id as string,status:r.status as LearningProgress['status'],totalReviews:r.total_reviews as number,correctCount:r.correct_count as number,incorrectCount:r.incorrect_count as number,firstTryCorrectCount:r.first_try_correct_count as number,streak:r.streak as number,lastReviewedAt:r.last_reviewed_at as number|undefined,nextReviewAt:r.next_review_at as number|undefined,lastWrongAttempts:r.last_wrong_attempts as number|undefined,ease:r.ease as number|undefined})
export async function loadCloudProgress(){if(!supabase)return{};const {data,error}=await supabase.from('learning_progress').select('*');if(error)throw error;return Object.fromEntries((data??[]).map(r=>[r.vocabulary_id,progressFromRow(r)])) as Record<string,LearningProgress>}
export async function saveCloudProgress(user:User,p:LearningProgress){if(!supabase)return;const {error}=await supabase.from('learning_progress').upsert({user_id:user.id,vocabulary_id:p.vocabularyId,status:p.status,total_reviews:p.totalReviews,correct_count:p.correctCount,incorrect_count:p.incorrectCount,first_try_correct_count:p.firstTryCorrectCount,streak:p.streak,last_reviewed_at:p.lastReviewedAt,next_review_at:p.nextReviewAt,last_wrong_attempts:p.lastWrongAttempts,ease:p.ease,updated_at:new Date().toISOString()});if(error)throw error}
export async function loadUserVocabulary():Promise<LoadedVocabulary[]>{if(!supabase)return[];const {data,error}=await supabase.from('user_vocabulary').select('*').order('created_at');if(error)throw error;return(data??[]).map(r=>({id:r.id,category:r.category,categoryZh:r.category_zh,conceptGroup:r.concept_group,lemma:r.lemma,sentence:r.sentence,translation:r.translation,answer:r.answer,targetType:r.target_type,aliases:r.aliases,confusionGroup:r.confusion_group,tags:r.tags,difficulty:r.difficulty,dataset:'custom'}))}
export async function uploadUserVocabulary(user:User,items:VocabularySource[]){if(!supabase)return;const rows=items.map(c=>({user_id:user.id,id:`custom:${c.id}`,category:c.category||'My Vocabulary',category_zh:c.categoryZh,concept_group:c.conceptGroup,lemma:c.lemma,sentence:c.sentence,translation:c.translation,answer:c.answer,target_type:c.targetType,aliases:c.aliases??[],confusion_group:c.confusionGroup,tags:c.tags??[],difficulty:c.difficulty??1}));const {error}=await supabase.from('user_vocabulary').upsert(rows);if(error)throw error}
