import { useEffect,useRef,useState } from 'react'
import { Navigate,useNavigate } from 'react-router-dom'
import { Eye,SkipForward,X } from 'lucide-react'
import { useDictation } from '../context/DictationContext'
import { canRevealDictationAnswer,DICTATION_REVEAL_SECONDS,sentenceAccuracy,sentenceDifferences,isExactSentence } from '../services/dictation'
import { loadDictationAttempts,saveDictationAttempt } from '../services/cloudRepository'
import type { DictationAttempt } from '../domain/dictation'
import { ProgressBar } from '../components/ProgressBar'

export function DictationPracticePage(){const {session,addResult}=useDictation(),navigate=useNavigate(),inputRef=useRef<HTMLTextAreaElement>(null),[draft,setDraft]=useState(''),[revealed,setRevealed]=useState(false),[seconds,setSeconds]=useState(0),[saving,setSaving]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<DictationAttempt[]>([]);const index=session?.results.length??0,card=session?.cards[index],cardHistory=history.filter(attempt=>attempt.vocabularyId===card?.id&&attempt.submissionType==='initial').reverse()
 useEffect(()=>{loadDictationAttempts().then(setHistory).catch(()=>setHistory([]))},[])
 useEffect(()=>{if(seconds<=0)return;const timer=window.setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[seconds])
 useEffect(()=>{if(revealed&&seconds===0)inputRef.current?.focus()},[revealed,seconds])
 if(!session)return <Navigate to="/"/>;if(!card)return <Navigate to="/dictation/summary"/>
 const toggleAnswer=()=>{if(seconds>0){setSeconds(0);return}if(!canRevealDictationAnswer(draft,seconds))return;setRevealed(true);setSeconds(DICTATION_REVEAL_SECONDS);setError('')}
 const persist=async(skipped:boolean)=>{if(saving)return;const submitted=skipped?'':draft,result={vocabularyId:card.id,submittedAnswer:submitted,isCorrect:!skipped&&isExactSentence(submitted,card.sentence),accuracy:skipped?0:sentenceAccuracy(submitted,card.sentence),wordDifferences:skipped?[]:sentenceDifferences(submitted,card.sentence),submissionType:skipped?'skipped' as const:'initial' as const,submittedAt:new Date().toISOString()};setSaving(true);setError('');if(skipped){void saveDictationAttempt(session.id,card,result).catch(e=>console.warn('[Dictation] skipped attempt could not be saved',e));addResult(result);setDraft('');setRevealed(false);setSeconds(0);setSaving(false);return}try{await saveDictationAttempt(session.id,card,result)}catch(e){setError(e instanceof Error?e.message:'保存失败，请重试');setSaving(false);return}addResult(result);setDraft('');setRevealed(false);setSeconds(0);setSaving(false)}
 return <div className="practice-page dictation-practice"><div className="practice-top"><button className="icon-button" onClick={()=>navigate('/')} aria-label="退出"><X/></button><div><span>{index+1} / {session.cards.length}</span><ProgressBar value={index} total={session.cards.length}/></div><span className="dataset-pill">句子默写</span></div><section className="dictation-card"><p className="eyebrow">WRITE THE FULL SENTENCE</p><h1>{card.translation}</h1><div className="dictation-score-history"><span>历史提交 {cardHistory.length} 次</span>{cardHistory.length>0&&<span className="score-chips">{cardHistory.map(attempt=><b className={attempt.isCorrect?'perfect':''} key={attempt.id}>{attempt.accuracy}</b>)}</span>}</div>{seconds>0?<div className="dictation-answer"><span>正确答案 · {seconds}s · 按 Enter 隐藏</span><strong>{card.sentence}</strong></div>:revealed?<div className="dictation-answer hidden-answer"><span>答案已隐藏</span><strong>可以继续修改，或再次按 Enter 查看答案</strong></div>:<p className="dictation-instruction"><Eye size={16}/>输入完整句子后按 Enter 查看答案</p>}<form onSubmit={event=>{event.preventDefault();toggleAnswer()}}><textarea ref={inputRef} autoFocus readOnly={seconds>0} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();toggleAnswer()}}} placeholder="输入完整英文句子…"/><button className="secondary" disabled={!draft.trim()}>{seconds>0?'按 Enter 隐藏答案':'按 Enter 查看答案'}</button></form>{error&&<p className="dictation-error">{error}</p>}<div className="dictation-actions"><button className="secondary" disabled={saving} onClick={()=>void persist(true)}><SkipForward size={17}/>跳过</button><button className="primary" disabled={saving||!revealed||seconds>0||!draft.trim()} onClick={()=>void persist(false)}>{saving?'正在保存…':'提交并进入下一题'}</button></div></section></div>}
