import { ArrowRight,BookOpen,Layers3,PenLine,Shapes,Sparkles } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { useSession } from '../context/SessionContext'
import { selectCards,type PracticeMode } from '../services/cardSelector'
import { getHomeStats } from '../services/homeStats'
import { useDictation } from '../context/DictationContext'
import { selectDictationCards } from '../services/dictation'
export function HomePage(){const {cards,progress,issues}=useApp(),{start}=useSession(),{start:startDictation}=useDictation(),navigate=useNavigate(),[now]=useState(()=>Date.now()),{dueToday,learning,mastered,newCount}=getHomeStats(cards,progress,now)
 const begin=(mode:PracticeMode)=>{const selected=selectCards(cards,progress,{mode,limit:20});if(!selected.length)return;start(selected,mode);navigate('/practice')}
 const beginDictation=()=>{const selected=selectDictationCards();if(!selected.length)return;startDictation(selected);navigate('/dictation')}
 const modes=[{mode:'vocabulary' as const,title:'普通词汇',sub:'词义 · 拼写 · 搭配',icon:BookOpen},{mode:'singular-plural' as const,title:'单复数',sub:'语境中的正确词形',icon:Shapes},{mode:'participles' as const,title:'分词形式',sub:'时态 · 变化 · 拼写',icon:Layers3},{mode:'writing' as const,title:'写作常用',sub:'Task 2 · 搭配 · 论证表达',icon:PenLine},{mode:'writing-singular-plural' as const,title:'写作-单复数',sub:'Task 2 · 可数性 · 单复数',icon:Shapes},{mode:'task2-core-concepts' as const,title:'task2-底层概念',sub:'Task 2 · 核心概念 · 因果关系',icon:Layers3},{mode:'custom' as const,title:'我的词库',sub:'练习个人上传内容',icon:BookOpen},{mode:'mistakes' as const,title:'易错词',sub:'集中攻克薄弱项',icon:Sparkles}]
 return <div className="page home"><section className="hero"><div><p className="eyebrow">LEXI CYCLE · ACTIVE RECALL</p><h1>把记住，变成<br/><em>真正会用。</em></h1><p className="lead">在真实语境中主动拼写。每一次回忆，都让记忆更牢固。</p><button className="primary" onClick={()=>begin('mixed')}>开始综合练习 <ArrowRight size={20}/></button></div><div className="orbit" aria-hidden="true"><div className="orb orb1">recall</div><div className="orb orb2">spell</div><div className="orb orb3">master</div><div className="core">LC</div></div></section><section className="stats"><div><strong>{dueToday}</strong><span>今日待复习</span></div><div><strong>{learning}</strong><span>学习中</span></div><div><strong>{newCount}</strong><span>新内容</span></div><div><strong>{mastered}</strong><span>已掌握</span></div></section><section><div className="section-head"><div><p className="eyebrow">FOCUS TRAINING</p><h2>专项训练</h2></div><span>每组 20 张卡片</span></div><div className="mode-grid"><button className="mode-card dictation-mode" onClick={beginDictation}><span className="mode-icon"><PenLine/></span><span><b>句子默写</b><small>中文提示 · 完整英文句子 · 历史追踪</small></span><ArrowRight size={18}/></button>{modes.map(({mode,title,sub,icon:Icon})=><button className="mode-card" key={mode} onClick={()=>begin(mode)}><span className="mode-icon"><Icon/></span><span><b>{title}</b><small>{sub}</small></span><ArrowRight size={18}/></button>)}</div></section>{import.meta.env.DEV&&issues.length>0&&<p className="validation-note">已跳过 {issues.length} 条异常数据，详情见控制台。</p>}</div>}
