import { Flame,Medal,Save,Trophy } from 'lucide-react'
import { useCallback,useEffect,useState,type FormEvent } from 'react'
import { useAuth } from '../context/AuthContext'
import { loadLeaderboard,updateUserProfile,type LeaderboardEntry,type LeaderboardPeriod } from '../services/cloudRepository'

const periods:{value:LeaderboardPeriod;label:string}[]=[{value:'today',label:'今日'},{value:'week',label:'本周'},{value:'all',label:'总榜'}]

export function LeaderboardPage(){const {profile,refreshProfile}=useAuth(),[period,setPeriod]=useState<LeaderboardPeriod>('week'),[entries,setEntries]=useState<LeaderboardEntry[]>([]),[nickname,setNickname]=useState(profile?.nickname??''),[enabled,setEnabled]=useState(profile?.leaderboardEnabled??true),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 const refresh=useCallback(async()=>{setLoading(true);setMessage('');try{setEntries(await loadLeaderboard(period))}catch(e){setMessage(e instanceof Error?e.message:'榜单加载失败')}finally{setLoading(false)}},[period])
 useEffect(()=>{queueMicrotask(()=>void refresh())},[refresh])
 useEffect(()=>{if(profile)queueMicrotask(()=>{setNickname(profile.nickname);setEnabled(profile.leaderboardEnabled)})},[profile])
 const save=async(e:FormEvent)=>{e.preventDefault();const value=nickname.trim();if(value.length<2||value.length>24||value.includes('@')){setMessage('昵称需要 2～24 个字符，且不能填写邮箱');return}try{await updateUserProfile({nickname:value,leaderboardEnabled:enabled});await refreshProfile();await refresh();setMessage('榜单设置已保存')}catch(error){setMessage(error instanceof Error?error.message:'保存失败，昵称可能已被使用')}}
 const me=entries.find(entry=>entry.isCurrentUser),ahead=me?entries.find(entry=>entry.rank<me.rank&&entry.rank===me.rank-1):undefined
 return <div className="page leaderboard-page"><div className="leaderboard-heading"><div><p className="eyebrow">FRIENDLY COMPETITION</p><h1>学习榜单</h1><p className="page-intro">认真回忆、稳定学习，一起把词汇量练上去。</p></div><Trophy className="leaderboard-trophy"/></div><div className="period-tabs">{periods.map(item=><button className={period===item.value?'active':''} key={item.value} onClick={()=>setPeriod(item.value)}>{item.label}</button>)}</div>{message&&<p className="leaderboard-message">{message}</p>}{loading?<div className="leaderboard-empty">正在加载榜单…</div>:entries.length===0?<div className="leaderboard-empty">还没有榜单数据，完成一组练习来抢占第一名吧。</div>:<><section className="podium">{entries.slice(0,3).map(entry=><div className={`podium-card place-${entry.rank}`} key={`${entry.rank}-${entry.nickname}`}><Medal/><span>第 {entry.rank} 名</span><strong>{entry.nickname}</strong><b>{entry.points} 分</b><small>{entry.newMasteredCount} 个新掌握</small></div>)}</section>{me&&<section className="my-rank"><div><span>我的排名</span><strong>#{me.rank}</strong></div><div><span>本期积分</span><strong>{me.points}</strong></div><div><span>首次正确率</span><strong>{me.accuracy}%</strong></div><div><span><Flame size={16}/>连续学习</span><strong>{me.studyStreak} 天</strong></div>{ahead&&<p>再得 {Math.max(1,ahead.points-me.points+1)} 分即可追上 {ahead.nickname}</p>}</section>}<section className="ranking-list"><div className="ranking-row ranking-head"><span>排名</span><span>昵称</span><span>积分</span><span>完成</span><span>新掌握</span><span>正确率</span><span>连续</span></div>{entries.map(entry=><div className={`ranking-row ${entry.isCurrentUser?'is-me':''}`} key={`${entry.rank}-${entry.nickname}`}><b>#{entry.rank}</b><strong>{entry.nickname}{entry.isCurrentUser&&<small> 我</small>}</strong><b>{entry.points}</b><span>{entry.completedCount}</span><span>{entry.newMasteredCount}</span><span>{entry.accuracy}%</span><span>{entry.studyStreak}天</span></div>)}</section></>}
 <section className="scoring-rules"><div><p className="eyebrow">SCORING</p><h2>积分规则</h2><p>今日榜和本周榜采用综合分，让练习质量和新掌握词汇都能影响排名。</p></div><div className="scoring-grid"><article><strong>有效练习量</strong><b>最高 200 分</b><span>每完成 1 张得 2 分，最多计算 100 张。</span></article><article><strong>首次正确率</strong><b>最高 300 分</b><span>正确率 × 样本系数 × 300；样本系数为完成数量 ÷ 40，最高为 1。</span></article><article><strong>新掌握数量</strong><b>最高 300 分</b><span>每个首次掌握的词得 15 分，最多计算 20 个。</span></article></div><p className="scoring-note">综合分满分 800 分。同分时依次比较新掌握数量、首次正确率、完成数量和达到当前成绩的时间。总榜保留历史累计积分，用于记录长期投入；连续学习天数仅作展示，不直接计分。</p></section>
 <form className="leaderboard-settings" onSubmit={save}><div><h2>榜单设置</h2><p>榜单只公开昵称和汇总成绩，不会显示邮箱、错词或个人词库。</p></div><label>公开昵称<input value={nickname} maxLength={24} onChange={e=>setNickname(e.target.value)}/></label><label className="leaderboard-toggle"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span>参与公开榜单</span></label><button className="secondary"><Save size={17}/>保存设置</button></form></div>}
