import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { essays,ideas,expressions,templates,paths,resources,readWritingDraft,saveWritingDraft,readWritingAttempts,saveWritingAttempt,syncWritingAttempt,syncWritingDraft,recoverWritingDraft,loadWritingHistory,wordCount,expressionMatches,type WritingTrack,type HintLevel,type WritingDraft,type WritingAttempt } from '../services/writing'
import { isExactSentence, sentenceDifferences } from '../services/dictation'
import '../writing.css'
const tracks:Record<WritingTrack,string>={templates:'范文与模板',ideas:'观点与展开',expressions:'句型与短语'}
const typeNames:Record<string,string>={opinion:'同意／不同意',outweigh:'利弊权衡',discussion:'双边讨论'}
const outlineLabels=['开头：任务与立场','主体一：理由／观点 A','主体二：理由／观点 B','回应或个人判断','结论']
const checks=['直接回应题目要求','原因与结果连贯','情景具体且相关','没有重复同一个理由','结论与立场一致']
const sentenceChecks=['表达符合本意','搭配和介词正确','主谓与词形正确','句子完整']
function checksFor(track:WritingTrack,exercise:string){if(track==='expressions')return exercise.endsWith(':transfer')?sentenceChecks:[];return exercise==='structure'?[]:checks}
function Reference({text}:{text:string}){return <div className="writing-reference">{text}</div>}
export function WritingPage(){const {user}=useAuth();const [params,setParams]=useSearchParams();const track=(Object.hasOwn(tracks,params.get('track')??'')?params.get('track'):'templates') as WritingTrack;const topic=essays.find(e=>e.id===params.get('topic'))??essays[0];const [tab,setTab]=useState<'practice'|'library'|'history'>('practice');const [search,setSearch]=useState('');const [history,setHistory]=useState<WritingAttempt[]>(()=>user?readWritingAttempts(user.id):[]);const [notice,setNotice]=useState('');
 const setContext=(nextTrack:WritingTrack,nextTopic=topic.id)=>setParams({track:nextTrack,topic:nextTopic});
 const refreshHistory=async()=>{if(!user)return;const local=readWritingAttempts(user.id);setHistory(local);try{const remote=await loadWritingHistory(user.id);setHistory([...new Map([...remote,...local].map(a=>[a.id,a])).values()].sort((a,b)=>b.submittedAt-a.submittedAt).slice(0,300));setNotice('记录已更新')}catch(e){setNotice((e as Error).message)}};
 return <div className="page writing-page"><p className="eyebrow">TASK 2 · WRITING PRACTICE</p><h1>把材料变成作文</h1><p className="page-intro">选结构，补逻辑，调用表达。用同一道题练到独立成文。</p><div className="writing-tabs">{Object.entries(tracks).map(([id,title])=><button className={track===id?'active':''} key={id} onClick={()=>setContext(id as WritingTrack)}>{title}</button>)}</div><label className="writing-topic">作文题目<select value={topic.id} onChange={e=>setContext(track,e.target.value)}>{essays.map(e=><option key={e.id} value={e.id}>Essay {e.number} · {e.title}</option>)}</select></label><section className="writing-panel"><span className="tag">{typeNames[topic.type]}</span><h2>{topic.prompt}</h2><small>{topic.promptSource}</small></section><div className="writing-tabs">{(['practice','library','history'] as const).map(id=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);if(id==='history')void refreshHistory()}}>{{practice:'开始练习',library:'资料库',history:'练习记录'}[id]}</button>)}</div>{notice&&<p role="status">{notice}</p>}
 {tab==='practice'&&user&&<WritingWorkspace key={`${user.id}:${track}:${topic.id}`} userId={user.id} track={track} topicId={topic.id} onNavigate={setContext}/>}
 {tab==='library'&&<><label className="writing-topic">搜索资料<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="观点、表达、范文内容…"/></label>{essays.filter(e=>`${e.title} ${e.prompt} ${e.paragraphs.map(p=>p.text).join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(e=><details className="writing-panel" key={e.id}><summary>Essay {e.number} · {e.title}</summary><p>{e.prompt} · {e.promptSource}</p>{e.paragraphs.map((p,i)=><section key={i}><h3>{p.role}</h3><p>{p.text}</p></section>)}{e.originalOpening&&<p>修订说明：原开头比较了网购与实体店的优点，已修正为网购的优势与劣势。原文：{e.originalOpening}</p>}</details>)}{ideas.filter(i=>`${i.title} ${i.chain} ${i.expansion}`.toLowerCase().includes(search.toLowerCase())).map(i=><details className="writing-panel" key={i.id}><summary>{i.id} · {i.title}</summary><p>{i.chain}</p><Reference text={i.expansion}/><p>来源：{i.sourceEssayIds.join('、')}</p></details>)}{expressions.filter(e=>`${e.answer} ${e.meaning}`.toLowerCase().includes(search.toLowerCase())).map(e=><details className="writing-panel" key={e.id}><summary>{e.answer} · {e.meaning}</summary><p>{e.sentence}</p><p>{e.translation}</p><p>{e.grammar} · {e.ideaIds.join('、')}</p><small>{e.source}</small></details>)}<h2>完整源材料</h2>{resources.map(r=><details className="writing-panel" key={r.title}><summary>{r.title}</summary><Reference text={r.body}/></details>)}</>}
 {tab==='history'&&<><p>最近最多保留 300 条记录。固定题显示正误；自主写作显示自查情况。</p>{history.length===0&&<p>尚无写作练习记录。</p>}{history.map(a=><details className="writing-panel" key={a.id}><summary>{tracks[a.track]} · {essays.find(e=>e.id===a.topic)?.title} · {new Date(a.submittedAt).toLocaleString()} · {a.elapsedSeconds} 秒</summary><p>{a.exercise} · 提示模式 {({guided:"有提示",recall:"少提示",independent:"独立练习"})[a.draft.hintLevel]} · 主动查看参考 {a.draft.hintViews} 次{checksFor(a.track,a.exercise).length>0?` · 自查 ${a.draft.checks.filter(c=>checksFor(a.track,a.exercise).includes(c)).length}/${checksFor(a.track,a.exercise).length}`:''}{a.fixedCorrect!==undefined?` · 固定表达${a.fixedCorrect?'正确':'需复习'}`:''}</p>{Object.entries(a.draft.fields).map(([key,value])=><p className="writing-reference" key={key}>{key}：{value}</p>)}<button className="secondary" onClick={()=>{if(user)void syncWritingAttempt(user.id,a).then(()=>setNotice('该记录已同步')).catch(e=>setNotice(e.message))}}>重试同步此记录</button></details>)}</>}
 <p><Link to="/">返回首页</Link></p></div>}
function WritingWorkspace({userId,track,topicId,onNavigate}:{userId:string;track:WritingTrack;topicId:string;onNavigate:(track:WritingTrack,topic:string)=>void}){const topic=essays.find(e=>e.id===topicId)!;const pool=[...ideas].sort((a,b)=>Number(b.sourceEssayIds.includes(topicId))-Number(a.sourceEssayIds.includes(topicId)));const attempts=readWritingAttempts(userId);const needsReview=(id:string)=>attempts.find(a=>a.exercise===`${id}:cloze`)?.fixedCorrect===false;const expressionPool=expressions.filter(e=>e.ideaIds.some(id=>topic.ideaIds.includes(id))).sort((a,b)=>Number(needsReview(b.id))-Number(needsReview(a.id)));const [exercise,setExercise]=useState(track==='templates'?'outline':track==='ideas'?pool[0].id:expressionPool[0].id);
 const modes=track==='templates'?[{id:'structure',title:'结构回忆'},{id:'outline',title:'提纲与模板'},{id:'essay',title:'整篇／迁移写作'}]:track==='ideas'?pool.map(i=>({id:i.id,title:`${i.sourceEssayIds.includes(topicId)?"本题参考 · ":"其他观点 · "}${i.id} ${i.title}`})):expressionPool.map((e,i)=>({id:e.id,title:`第 ${i+1} 题 · ${e.meaning}${needsReview(e.id)?" · 需复习":""}`}));
 return <><label className="writing-topic">练习内容<select value={exercise} onChange={e=>setExercise(e.target.value)}>{modes.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><WritingEditor key={`${track}:${topicId}:${exercise}`} userId={userId} track={track} topicId={topicId} exercise={exercise}/><div className="writing-actions"><button className="secondary" onClick={()=>onNavigate('templates',topicId)}>练文章结构</button><button className="secondary" onClick={()=>onNavigate('ideas',topicId)}>练观点展开</button><button className="secondary" onClick={()=>onNavigate('expressions',topicId)}>练相关表达</button>{track==='templates'&&<button className="primary" onClick={()=>setExercise('essay')}>进入整篇写作</button>}{track==='expressions'&&<button className="secondary" onClick={()=>{const index=expressionPool.findIndex(e=>e.id===exercise);setExercise(expressionPool[(index+1)%expressionPool.length].id)}}>下一题</button>}</div></>}
function WritingEditor({userId,track,topicId,exercise}:{userId:string;track:WritingTrack;topicId:string;exercise:string}){const workspaceId=`${topicId}:${track}:${exercise}`;const lastSubmission=useRef<{signature:string;attempt:WritingAttempt}|null>(null);const previousError=useRef(false);const referenceWasShown=useRef(false);const [draft,setDraft]=useState<WritingDraft>(()=>({...readWritingDraft(userId,workspaceId),hintLevel:'independent'}));const [reference,setReference]=useState(()=>draft.hintLevel==='guided');const [result,setResult]=useState<boolean|null>(null);const [notice,setNotice]=useState('');const [saving,setSaving]=useState(false);const [storageIssue,setStorageIssue]=useState('');const [now,setNow]=useState(()=>Date.now());const [expressionMode,setExpressionMode]=useState<'cloze'|'sentence'|'transfer'>('cloze');const topic=essays.find(e=>e.id===topicId)!;const idea=ideas.find(i=>i.id===exercise);const expression=expressions.find(e=>e.id===exercise);const template=templates.find(t=>t.id===(draft.fields.taskType||topic.type))??templates[0];const activeChecks=checksFor(track,track==='expressions'?`${exercise}:${expressionMode}`:exercise);
 useEffect(()=>{try{saveWritingDraft(userId,workspaceId,draft)}catch{queueMicrotask(()=>setStorageIssue('本机草稿保存失败，请先复制内容备份。'))}},[userId,workspaceId,draft]);
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[]);
 const update=(key:string,value:string)=>setDraft(d=>({...d,fields:{...d.fields,[key]:value},updatedAt:Date.now()}));
 const reveal=()=>{setReference(value=>!value);if(!reference){referenceWasShown.current=true;setDraft(d=>({...d,hintViews:d.hintViews+1}))}};
 const field=(key:string,label:string,large=false)=><label className="writing-field" key={key}>{label}<textarea readOnly={saving} rows={large?12:3} value={draft.fields[key]??''} onChange={e=>{update(key,e.target.value);setResult(null)}} placeholder="在这里写下你的回答…"/></label>;
 const saveCloud=async()=>{setSaving(true);try{saveWritingDraft(userId,workspaceId,draft);await syncWritingDraft(userId,workspaceId,draft);setNotice('草稿已同步到云端')}catch(e){setNotice((e as Error).message)}finally{setSaving(false)}};
 const submit=async(submittedAt:number)=>{if(!(track==='expressions'?(draft.fields[expressionMode==='cloze'?'answer':expressionMode==='sentence'?'sentence':'transferSentence']??'').trim():Object.entries(draft.fields).some(([key,value])=>!['chosenIdeas','taskType','newPrompt'].includes(key)&&value.trim()))){setNotice('请先填写练习内容');return}const fixed=track==='expressions'&&expressionMode==='cloze'?expressionMatches(draft.fields.answer??'',expression!):undefined;if(fixed!==undefined)setResult(fixed);const signature=JSON.stringify({fields:draft.fields,expressionMode,startedAt:draft.startedAt});const attempt:WritingAttempt=lastSubmission.current?.signature===signature?lastSubmission.current.attempt:{id:crypto.randomUUID(),workspaceId,track,topic:topicId,exercise:track==='expressions'?`${exercise}:${expressionMode}`:exercise,draft:{...draft,checks:draft.checks.filter(c=>activeChecks.includes(c))},elapsedSeconds:Math.max(0,Math.floor((submittedAt-draft.startedAt)/1000)),fixedCorrect:fixed,firstTryCorrect:fixed===undefined?undefined:fixed&&draft.hintLevel==='independent'&&draft.hintViews===0&&!referenceWasShown.current&&!previousError.current,submittedAt};lastSubmission.current={signature,attempt};if(fixed===false)previousError.current=true;setSaving(true);try{saveWritingAttempt(userId,attempt);await syncWritingAttempt(userId,attempt);await syncWritingDraft(userId,workspaceId,draft);setNotice(activeChecks.length?'练习已记录并同步，请结合参考内容自查。':'练习已记录并同步。')}catch(e){setNotice((e as Error).message)}finally{setSaving(false)}};
 return <section className="writing-panel"><div className="writing-controls"><label>提示等级<select disabled={saving} value={draft.hintLevel} onChange={e=>{setDraft(d=>({...d,hintLevel:e.target.value as HintLevel,updatedAt:Date.now()}));setReference(e.target.value==='guided');if(e.target.value==='guided')referenceWasShown.current=true}}><option value="guided">有提示</option><option value="recall">少提示</option><option value="independent">独立练习</option></select></label><span>开始至今 {Math.max(0,Math.floor((now-draft.startedAt)/60000))} 分钟 · 主动查看参考 {draft.hintViews} 次</span></div>
 {draft.hintLevel!=='independent'&&<p>{track==='templates'?'回应题目 → 两个主体理由／双方观点 → 回应与判断 → 结论':track==='ideas'?`${idea?.title}：观点 → 机制 → 情景 → 结果`:'根据具体语境调用表达，替换时检查主语、词形和介词。'}</p>}
 <button disabled={saving} className="secondary" aria-expanded={reference} aria-controls="writing-reference-panel" onClick={reveal}>{reference?'隐藏参考':'查看参考与自查依据'}</button>
 {reference&&<div id="writing-reference-panel" className="writing-hints">{track==='templates'?<><Reference text={template.body}/><details><summary>本题范文拆解</summary>{topic.paragraphs.map((p,i)=><div key={i}><h3>{p.role}</h3><p>{p.text}</p></div>)}</details></>:track==='ideas'?<><p>{idea?.chain}</p><Reference text={idea?.expansion??''}/>{paths.map(p=><details key={p.id}><summary>路径 {p.id}：{p.title}</summary><Reference text={p.body}/></details>)}</>:<><p>{expression?.answer} · {expression?.meaning}</p><p>{expression?.sentence}</p><p>{expression?.grammar}</p><small>{expression?.source}</small></>}</div>}
 {track==='templates'&&<>{exercise==='structure'?field('structure','回忆本题的段落顺序，并解释每段的任务'):exercise==='outline'?<>{field('stance','题型、立场与理由选择')}<fieldset className="writing-checks"><legend>选择支持理由（可以多选；相关性由你判断）</legend>{ideas.map(i=><label key={i.id}><input type="checkbox" checked={(draft.fields.chosenIdeas??'').split(',').includes(i.id)} onChange={e=>{const chosen=(draft.fields.chosenIdeas??'').split(',').filter(Boolean);update('chosenIdeas',(e.target.checked?[...chosen,i.id]:chosen.filter(id=>id!==i.id)).join(','))}}/>{i.id} {i.title}{i.sourceEssayIds.includes(topicId)?' · 本题范文使用':''}</label>)}</fieldset>{outlineLabels.map((label,i)=>field(`paragraph-${i+1}`,label))}</>:<>{field('newPrompt','迁移题目（可选：输入你想练的新题；留空使用上方题目）')}<label className="writing-topic">本次写作题型<select disabled={saving} value={draft.fields.taskType||topic.type} onChange={e=>update('taskType',e.target.value)}>{Object.entries(typeNames).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label>{field('essayOutline','提纲与观点因果链')}{field('essay','完整作文',true)}<p>英文单词数：{wordCount(draft.fields.essay??'')} · 自主写作不按范文逐字匹配。</p><details><summary>查看本题已保存的提纲／段落，便于继续写作</summary>{['outline',...ideas.filter(i=>i.sourceEssayIds.includes(topicId)).map(i=>i.id)].map(id=>{const saved=readWritingDraft(userId,`${topicId}:${id==='outline'?'templates':'ideas'}:${id}`);return <div key={id}><h3>{id}</h3>{Object.values(saved.fields).map((v,i)=><p className="writing-reference" key={i}>{v}</p>)}</div>})}</details></>}</>}
 {track==='ideas'&&<>{field('view','观点：谁获得什么好处／受到什么影响？')}{field('mechanism','机制：原来的困难 → 做法改变了什么？')}{field('scenario','具体情景：什么人，在什么情况下？')}{field('outcome','结果与意义：为什么支持你的判断？')}{field('paragraph','将以上逻辑写成英文段落',true)}</>}
 {track==='expressions'&&expression&&<><div className="writing-tabs">{(['cloze','sentence','transfer'] as const).map(mode=><button key={mode} className={expressionMode===mode?'active':''} onClick={()=>{setExpressionMode(mode);setResult(null)}}>{{cloze:'短语挖空',sentence:'核心句复现',transfer:'迁移造句'}[mode]}</button>)}</div>{expressionMode==='cloze'?<><p>{expression.translation}</p><p className="writing-cloze">{expression.sentence.replace(expression.answer,'__________')}</p>{field('answer',`输入短语：${expression.meaning}`)}{result!==null&&<p role="status">{result?'固定表达正确':'固定表达需复习，可查看参考后再次尝试。'}</p>}</>:expressionMode==='sentence'?<><p>{expression.translation}</p>{field('sentence','复现目标句（提交后打开参考核对，记录为复现练习）')}{reference&&draft.fields.sentence&&<p>复现核对：{isExactSentence(draft.fields.sentence,expression.sentence)?'与目标句一致':sentenceDifferences(draft.fields.sentence,expression.sentence).map(d=>`${d.actual??'缺失'} → ${d.expected??'多余'}`).join('；')||'请核对标点'}。这只是文本核对，不是写作能力评分。</p>}</>:<>{field('transferTopic','换一个相关话题，说明你想表达的逻辑')}{field('transferSentence',`用“${expression.meaning}”的表达写出新句子`)}<p>合法表达不限于参考句，请自查语法与因果关系。</p></>}</>}
 <>{activeChecks.length>0&&<fieldset className="writing-checks"><legend>{track==='expressions'?'造句自查':'自主输出自查（自行确认，不代表自动评分）'}</legend>{activeChecks.map(check=><label key={check}><input type="checkbox" disabled={saving} checked={draft.checks.includes(check)} onChange={e=>setDraft(d=>({...d,updatedAt:Date.now(),checks:e.target.checked?[...d.checks,check]:d.checks.filter(c=>c!==check)}))}/>{check}</label>)}</fieldset>}</><div className="writing-actions"><button disabled={saving} className="primary" onClick={()=>void submit(Date.now())}>{saving?'正在保存…':'记录本次练习'}</button><button disabled={saving} className="secondary" onClick={()=>void saveCloud()}>保存草稿到云端</button><button disabled={saving} className="secondary" onClick={()=>{setSaving(true);void recoverWritingDraft(userId,workspaceId).then(remote=>{if(!remote){setNotice('没有云端草稿');return}if(remote.updatedAt<draft.updatedAt){setNotice('本机草稿更新，已保留本机内容');return}setDraft(remote);setReference(remote.hintLevel==='guided');if(remote.hintLevel==='guided')referenceWasShown.current=true;setNotice('已恢复云端草稿')}).catch(e=>setNotice(e.message)).finally(()=>setSaving(false))}}>恢复较新的云端草稿</button><button disabled={saving} className="secondary" onClick={()=>{lastSubmission.current=null;previousError.current=false;referenceWasShown.current=reference;setDraft(d=>({...d,startedAt:Date.now(),hintViews:0}));setNotice('计时与提示次数已重新开始，内容保留')}}>重新计时</button></div>{storageIssue&&<p role="alert">{storageIssue}</p>}<p role="status">{notice||'输入会自动保存到当前账户的本机草稿；点击保存可同步到其他设备。'}</p></section>}
