import { StrictMode,type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import { createBrowserRouter,RouterProvider } from 'react-router-dom'
import { AppShell } from './components/AppShell'
import { AppProvider } from './context/AppContext'
import { SessionProvider } from './context/SessionContext'
import { HomePage } from './pages/HomePage'
import { PracticePage } from './pages/PracticePage'
import { SummaryPage } from './pages/SummaryPage'
import { VocabularyPage } from './pages/VocabularyPage'
import { MistakesPage } from './pages/MistakesPage'
import { UploadPage } from './pages/UploadPage'
import { AuthPage } from './pages/AuthPage'
import { LeaderboardPage } from './pages/LeaderboardPage'
import { AuthProvider } from './context/AuthContext'
import { ProtectedRoute } from './components/ProtectedRoute'
import { DictationProvider } from './context/DictationContext'
import { DictationPracticePage } from './pages/DictationPracticePage'
import { DictationSummaryPage } from './pages/DictationSummaryPage'
import { DictationHistoryPage } from './pages/DictationHistoryPage'
import './styles.css'
import './homeStats.css'
const protect=(node:ReactNode)=><ProtectedRoute>{node}</ProtectedRoute>
const router=createBrowserRouter([{path:'/login',element:<AuthPage/>},{element:protect(<AppShell/>),children:[{path:'/',element:<HomePage/>},{path:'/vocabulary',element:<VocabularyPage/>},{path:'/upload',element:<UploadPage/>},{path:'/mistakes',element:<MistakesPage/>},{path:'/leaderboard',element:<LeaderboardPage/>},{path:'/dictation-history',element:<DictationHistoryPage/>}]},{path:'/practice',element:protect(<PracticePage/>)},{path:'/summary',element:protect(<SummaryPage/>)},{path:'/dictation',element:protect(<DictationPracticePage/>)},{path:'/dictation/summary',element:protect(<DictationSummaryPage/>)}])
createRoot(document.getElementById('root')!).render(<StrictMode><AuthProvider><AppProvider><SessionProvider><DictationProvider><RouterProvider router={router}/></DictationProvider></SessionProvider></AppProvider></AuthProvider></StrictMode>)
